#!/bin/bash
# 此脚本用作 macOS 快捷指令"绘制虚拟内存图"的入口。参考 "macOS" "快捷指令" "运行 Shell 脚本"
# set -x

# workingDir 是你存放项目的目录
if [ -z "$workingDir" ]; then
  export workingDir="$HOME/Documents/Projects"
fi

i=1

echo -e "\n$((i++)). 打开 OmniGraffle 应用"
running=$(pgrep -x "OmniGraffle")
open -a "OmniGraffle" "$workingDir/learn-graffle/docs/README.graffle"
# 如果之前未打开程序，等待程序打开；之前已经处于运行状态，不用等待
if [ -z "$running" ]; then
  sleep 3
fi

cd "$workingDir/learn-graffle/automation" || exit
echo -e "\n$((i++)). 绘制虚拟内存图"
make demo-memory.case >/dev/null
